### ISSUE TITLE
Issues with regex

### ISSUE THREAD

**Issue by PauloGDPeixoto** [seifchen/kong-path-allow#2]
This plugin is very useful, excellent idea!
I'm only having some issues with the regex matching.
First of all, it won't let me escape the first slash:
` in 'services':
  - in entry 3 of 'services':
    in 'routes':
      - in entry 1 of 'routes':
        in 'plugins':
          - in entry 2 of 'plugins':
            in 'config':
              in 'allow_paths':
                - in entry 1 of 'allow_paths': should start with: /
                - in entry 2 of 'allow_paths': should start with: /
                - in entry 3 of 'allow_paths': should start with: / `
And also a regex that I validated in some regex testers does not work as well:
`- in entry 1 of 'allow_paths': invalid path: '/path/api/v1/site/[^\/ \#]+$' (characters outside of the reserved list of RFC 3986 found)`

**Comment by seifchen** [comment]
I think it’s okay to start with / because it can avoid many problems.
the second issuse:
Can you provide steps to reproduce？

**Comment by PauloGDPeixoto** [comment]
Yeah, I've found a post staging that it's okay to start with the non-escaped slash, sorry.
As for the second issue, I'm trying to match the following route
`/path/api/v1/site/SaksQZd2vdA1vmxdwpLvqCpyvpkmHrp8ltY7jvs3rYFb-0a2R`
This id in the last part of the url is random, does not have a fixed size, and the regex must stop with it, as I need to match other routes that have other stuff in front of the id.

**Comment by seifchen** [comment]
@PauloGDPeixoto Please tell me what you want and what you got, It would be better if there are steps to reproduce.

**Comment by PauloGDPeixoto** [comment]
So I've added this configuration:
```
- name: path-allow
  config:
    allow_paths:
    - /path/api/v1/site/[^\/ \#]+$
    - /path/api/v1/site/[^\/ \#]+/[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}$
    - /path/api/v1/site/[^\/ \#]+$\/[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}/submit$
    regex: true
```
And with these I expect to match the following routes:
```
/path/api/v1/site/SaksQZd2vdA1vmxdwpLvqCpyvpkmHrp8ltY7jvs3rYFb-0a2R
/path/api/v1/site/SaksQZd2vdA1vmxdwpLvqCpyvpkmHrp8ltY7jvs3rYFb-0a2R/19673ac0-1d75-4fba-b289-7dfb9c67462a
/path/api/v1/site/SaksQZd2vdA1vmxdwpLvqCpyvpkmHrp8ltY7jvs3rYFb-0a2R/19673ac0-1d75-4fba-b289-7dfb9c67462a/submit
```
For reference, I don't want to allow something like:
`/path/api/v1/site/SaksQZd2vdA1vmxdwpLvqCpyvpkmHrp8ltY7jvs3rYFb-0a2R/19673ac0-1d75-4fba-b289-7dfb9c67462a/other_value`

The regexes work as intended in a validator.
